<a href="https://colab.research.google.com/github/Fatimanridegreeclg/Mini-project-/blob/main/Introduction_to_numpy_class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Recap
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
type (arr)

numpy.ndarray

In [ ]:
#Dot product-m×n||n×p
arr1=np.random.randint(1,2,(3,1))
arr=np.random.randint(1,2,(1,2))

In [ ]:
arr.shape
arr1.shape

(3, 1)

In [ ]:
result=np.dot(arr,arr1)

In [ ]:
print (result)

[[ 6]
 [15]]


In [ ]:
r1=np.random.randint(10,20,(3,3))
print(r1)

[[19 13 16]
 [17 17 13]
 [10 13 16]]


In [ ]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# r1.I
result2=np.dot(r1,r2)

In [ ]:
print(result2)

[[19. 13. 16.]
 [17. 17. 13.]
 [10. 13. 16.]]


In [ ]:
#M.I=I.M=I
#A.B!=B.A

In [ ]:
#Mathematical operations
# + - * /
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [ ]:
print(t1)
print(t2)

[[5 4 5]
 [3 5 5]
 [5 5 3]]
[[5 5 3]
 [5 5 3]
 [4 4 5]]


In [ ]:
t3=t1+t2

In [ ]:
print(t3)

[[10  9  8]
 [ 8 10  8]
 [ 9  9  8]]


In [ ]:
#Matrix multiplication
result=np.dot(arr1,arr)

In [ ]:
#Statistical operations
mean=t3.mean()
mode=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [ ]:
print(mean)

8.777777777777779


In [ ]:
print(median)

9.0


In [ ]:
print(std)

0.7856742013183861


In [ ]:
print(var)

0.6172839506172838


In [ ]:
std*std

0.6172839506172838

In [ ]:
#Trignometry functions
#Sin(x)
#Cos(x)
#Tan(x)-sin(x)/cos(x)
#Cosec-1/sin(x)
#Sec-1/Cos(x)
#Cot-1/Tan(x)
#
angles=np.array([0,15,30,45,60,75,90])
#Sin(array)
result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [ ]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [ ]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapedarr=arr.reshape(3,2)
print(reshapedarr)
#Covert/Flatten any n dim array
flattendarr=arr.flatten()
print(flattendarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
#stacking the dataarr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapedarr=arr.reshape(3,2)
print(reshapedarr)
#Covert/Flatten any n dim array
flattendarr=arr.flatten()
print(flattendarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
#Filtering
arr=np.array([10,20,30,40,50,60,70,80,90])
farr=arr[arr>40]
print(farr)

[50 60 70 80 90]
